version: "2"
services:

  referencedata:
    image: openlmis/referencedata
    links:
      - db
      - log
    env_file: .env
    environment:
      JAVA_OPTS: '-server -Xmx1024m -Dlogging.config=/config/log/logback.xml'

  db:
    image: openlmis/postgres:9.6-postgis
    ports:
      - "5432"
    env_file: .env

  log:
    image: openlmis/rsyslog:1
    volumes:
      - '../logs/referencedata:/var/log'
