version: "2"
services:

  auth:
    image: openlmis/referencedata
    links:
      - db
      - log
    env_file: .env

  db:
    image: openlmis/postgres
    ports:
      - "8766:5432"
    env_file: .env

  log:
    image: openlmis/rsyslog
    volumes:
      - '../logs/referencedata:/var/log'
