version: "2"
services:
  referencedata:
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8080
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
