version: "2"
services:

  referencedata:
    image: openlmis/referencedata
    ports:
      - "8080"
    links:
      - db
      - log
    env_file: .env

  db:
    image: openlmis/postgres
    env_file: .env

  log:
    image: openlmis/rsyslog
    volumes:
      - '../logs/referencedata:/var/log'
