modules:
  console:
    disable: true
    screen: console
  jmeter:
    properties:
      base-uri: http://localhost
      basic-auth: user-client:changeme
      username: administrator
      password: password
    xml-jtl-flags:
      responseData: true
