modules:
  jmeter:
    properties:
      base-uri: http://localhost
      basic-auth: user-client:changeme
      username: administrator
      password: password
      # concurrency is in virtual users and duration is in seconds
      scenario-concurrency: 30
      scenario-duration: 30
    xml-jtl-flags:
      responseData: true
    memory-xmx: 4G
  local:
    sequential: true
reporting:
  - module: final-stats
