modules:
  jmeter:
    properties:
      base-uri: http://localhost
      basic-auth: user-client:changeme
      service-auth: trusted-client:secret
      username: administrator
      password: password
      # concurrency is in virtual users and duration is in seconds
      scenario-concurrency: 3
      scenario-duration: 30
    xml-jtl-flags:
      responseData: true
    memory-xmx: 4G
  local:
    sequential: true
reporting:
  - module: final-stats
  - module: passfail
    criteria:
    - failures>0%, stop as failed
# the following scenarios are common for all performance tests
# scenarios related with one of available resources should be
# put in separate file in `tests` directory
scenarios:
  get-user-token:
    requests:
      - if: '${__javaScript(vars.get("access_token") == null)}'
        then:
          - url: ${__P(base-uri)}/api/oauth/token
            method: POST
            label: GetUserToken
            headers:
              Authorization: Basic ${__base64Encode(${__P(basic-auth)})}
            body:
              grant_type: password
              username: ${__P(username)}
              password: ${__P(password)}
            extract-jsonpath:
              access_token:
                jsonpath: $.access_token
  get-service-token:
    requests:
      - if: '${__javaScript(vars.get("service_token") == null)}'
        then:
          - url: ${__P(base-uri)}/api/oauth/token
            method: POST
            label: GetServiceToken
            headers:
              Authorization: Basic ${__base64Encode(${__P(service-auth)})}
            body:
              grant_type: client_credentials
            extract-jsonpath:
              service_token:
                jsonpath: $.access_token
