modules:
  jmeter:
    properties:
      base-uri: http://localhost
      basic-auth: user-client:changeme
      username: administrator
      password: password
      # this property should always be expressed in unit of seconds.
      scenario-duration: 300
    xml-jtl-flags:
      responseData: true
reporting:
  - module: final-stats
