DELETE FROM referencedata.role_rights
WHERE rightid IN (
  SELECT id FROM referencedata.rights
  WHERE type = 'REPORTS' AND name IN (
    'REPORTING_RATE_AND_TIMELINESS_REPORT_VIEW',
    'STOCK_STATUS_REPORT_VIEW',
    'STOCKOUTS_REPORT_VIEW',
    'CONSUMPTION_REPORT_VIEW',
    'ORDERS_REPORT_VIEW',
    'ADJUSTMENTS_REPORT_VIEW',
    'ADMINISTRATIVE_REPORT_VIEW'
  )
);

DELETE FROM referencedata.right_assignments
WHERE rightname IN (
  'REPORTING_RATE_AND_TIMELINESS_REPORT_VIEW',
  'STOCK_STATUS_REPORT_VIEW',
  'STOCKOUTS_REPORT_VIEW',
  'CONSUMPTION_REPORT_VIEW',
  'ORDERS_REPORT_VIEW',
  'ADJUSTMENTS_REPORT_VIEW',
  'ADMINISTRATIVE_REPORT_VIEW'
);

DELETE FROM referencedata.rights
WHERE type = 'REPORTS' AND name IN (
  'REPORTING_RATE_AND_TIMELINESS_REPORT_VIEW',
  'STOCK_STATUS_REPORT_VIEW',
  'STOCKOUTS_REPORT_VIEW',
  'CONSUMPTION_REPORT_VIEW',
  'ORDERS_REPORT_VIEW',
  'ADJUSTMENTS_REPORT_VIEW',
  'ADMINISTRATIVE_REPORT_VIEW'
);